sheetNames = sheetnames("AQIrank.xls") 
% 读入table, z=sheet number;
data = readtable('AQIrank.xls',"ReadRowNames",false,"ReadVariableNames",false,"Sheet",sheetNames{1},"Range","B32:Y58"); 
data = data{:,:} ;
B = bar(data,"stacked")
set(gca,'xticklabel',{'SH',...
    'NJ','WX','CZ','SZ','NT','YC','YZ','ZJ','TiZ',...
    'HaZ','NB','WZ','JX','HuZ','SX','JH','ZS','TZ',...
    'HF','WH','MS','TL','AQ','CuZ','CiZ','XC'});
legend('Jan,19','Feb,19','Mar,19','Apr,19','May,19','Jun,19','Jul,19','Aug,19','Sep,19','Oct,19','Nov,19','Dec,19',...
    'Jan,20','Feb,20','Mar,20','Apr,20','May,20','Jun,20','Jul.20','Aug,20','Sep,20','Oct,20','Nov,20','Dec,20',...
    'location','southoutside','NumColumns',12);
legend boxoff;